CC = g++ -std=c++11
sanitize = -fsanitize=leak
FLAGS = -g -Wall -pedantic

main: main.cpp
	$(CC) $(FLAGS) main.cpp -o main.out
	./main.out
factoral: factoral.cpp
	$(CC) $(FLAGS) factoral.cpp -o factoral.out
	./factoral.out

prime: prime.cpp
	$(CC) $(FLAGS) prime.cpp -o prime.out
	./prime.out

matrix: matrix.cpp
	$(CC) $(FLAGS) matrix.cpp -o matrix.out
	./matrix.out
